# Generated by Django 3.2 on 2023-04-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agenda_telefonica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda_telefonica',
            options={'ordering': ['area_persona'], 'verbose_name_plural': 'Agenda_telefónica'},
        ),
        migrations.AlterField(
            model_name='agenda_telefonica',
            name='area_persona',
            field=models.CharField(help_text='Área o Persona', max_length=120, verbose_name='Área/Persona'),
        ),
        migrations.AlterField(
            model_name='agenda_telefonica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='agenda_telefonica',
            name='numero',
            field=models.CharField(help_text='Número o Extensión', max_length=80, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='agenda_telefonica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='nombre',
            field=models.CharField(help_text='Agrege nueva área', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='asunto',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='asunto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='asunto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='registro',
            field=models.CharField(help_text='Descripción del registro', max_length=250, verbose_name='RegistroXs'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
