# Generated by Django 3.2 on 2023-04-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230413_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda_telefonica',
        ),
    ]
